### ISSUE TITLE
Enable ESLint for Theodul Player

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#1201]
We should run ESLint on all Theodul player components:

 - [x] engage-theodul-core (#1107)
 - [x] engage-theodul-plugin-controls (#1198)
 - [x] engage-theodul-plugin-custom-matomo (#1909)
 - [x] engage-theodul-plugin-custom-mhConnection (#1909)
 - [x] engage-theodul-plugin-custom-notifications (#1909)
 - [x] <strike>engage-theodul-plugin-custom-usertracking</strike> (#1902)
 - [x] engage-theodul-plugin-description (#1909)
 - [x] engage-theodul-plugin-tab-description (#1909)
 - [x] engage-theodul-plugin-tab-shortcuts (#1909)
 - [x] engage-theodul-plugin-tab-slidetext (#1909)
 - [x] <strike>engage-theodul-plugin-timeline-statistics</strike> (#1902)
 - [x] engage-theodul-plugin-video-videojs (#1909)

**Comment by lkiesow** [comment]
If someone grabs this for Hacktoberfest: Getting this done for only some modules would already be quite nice.
