### ISSUE TITLE
Enforce Maven Dependency Check

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast#1893]
Most of Opencast's modules use the maven-dependency-pligin to ensure dependencies are specified correctly:

https://github.com/opencast/opencast/blob/a67ece488617d23101e16357ab5da0c69105644b/modules/animate-impl/pom.xml#L88-L98

Some modules still have an exception though because no one found the time to fix them until now:

https://github.com/opencast/opencast/blob/a67ece488617d23101e16357ab5da0c69105644b/docs/checkstyle/maven-dependency-plugin.exceptions#L1-L17

You can check which dependencies are problematic by running `mvn dependency:analyze` in the module directory (you need one full Opencast build before you can do that). Note that you may need to specify exceptions since for things which are dynamically loaded at runtime (like the logger in the example above).

---

List of missing modules:

- [x] `modules/admin-ui/pom.xml` (#1904)
- [x] `modules/asset-manager-impl/pom.xml` (#2033)
- [x] `modules/asset-manager-storage-aws/pom.xml` (#2050)
- [x] `modules/common-jpa-impl/pom.xml` (#2053)
- [x] `modules/common/pom.xml` (#2053)
- [x] `modules/cover-image-impl/pom.xml` (#2053)
- [x] `modules/db/pom.xml`  (#1957)
- [x] `modules/distribution-service-aws-s3/pom.xml` (#2065)
- [x] `modules/external-api/pom.xml` (#2065)
- [x] `modules/index-service/pom.xml` (#2065)
- [x] `modules/oaipmh-persistence/pom.xml`  (#2065)
- [x] `modules/publication-service-youtube-v3/pom.xml` (#1904)
- [x] `modules/scheduler-impl/pom.xml`  (#2065)
- [x] `modules/search/pom.xml` (#1904)
- [x] `modules/search-service-impl/pom.xml`
- [x] `modules/security-shibboleth/pom.xml`  (#2065)
- [x] `modules/solr/pom.xml` 

---

For anyone working on this: Don't hesitate to submit pull requests fixing only some modules.

**Comment by SijmenHuizenga** [comment]
I will give this a shot. Do you prefer a pr for each module individually or rather many together?

**Comment by gregorydlogan** [comment]
Fewer PRs would be better IMO.

**Comment by lkiesow** [comment]
Yep, I agree. We don't mind if you split this – if you have one part running and have a problem, don't wait until everything is done – but if you work on it at one time anyway, putting multiple modules in one pull request is easier for everyone. Also, don't hesitate to ask if you have questions about dependencies.

Also, pull request #1886 already fixes the dependencies for `search-service-impl`. So, no need to work on that one.

**Comment by SijmenHuizenga** [comment]
Thanks! I've started working on `publication-service-youtube-v3`. It compiles (yay) but still need to test if it actually works... Draft pr to show what's going on in #1904

**Comment by SijmenHuizenga** [comment]
#1904 now has fixes for the following modules:

*  modules/admin-ui/pom.xml
*  modules/publication-service-youtube-v3/pom.xml
*  modules/search/pom.xml

Since my weekend is coming to an end I will leave it at this.
