### ISSUE TITLE
Reformat code according to checkstyle 

### ISSUE THREAD

**Issue by LukasKalbertodt** [opencast/opencast#2238]
Starting with #2216, we have some checkstyle-rules which have exceptions defined for specific files/modules. We want to get rid of those exceptions one by one. So this issue tracks the progress of correctly formatting the code and removing those exceptions in `checkstyle-suppressions.xml`.

I plan on doing a good chunk of this work myself, but obviously, there is a lot to do. Both, fixing the code *and* reviewing all the changes will take quite some time. In case this helps anyone, my workflow for this is roughly like this:

<details>
<summary>My workflow for working on this</summary>

- Temporarily set `<failOnViolation>` and `<failsOnError>` to `false` in `pom.xml`
- Remove one or multiple line from `checkstyle-suppressions.xml` 
  - *Note*: if you remove one line for module `foo`, you should probably remove all lines for that module, including other style rules. If you are working on some files anyway, it's probably best to fix all issues at once.
- Run `mvn checkstyle:check 2>&1 | grep "\[ERROR\]"`
- Use the output of that command to somehow quickly open files in your editor. For example, I use Sublime Text and I would process that output such that I get a file with lines in the format `filename.java:linenumber`. Then, I can do the following:
  - ctrl+x to cut the current line
  - ctrl+p & ctrl+v & enter to navigate to that file and to the specific line number
  - Fix the code
  - ctrl+s & ctrl+w & repeat

</details>

## Modules

If modules get fixed, this list should be updated (I imagine enough people can edit this comment, so that should be fine). The numbers in parenthesis mean count the different violations:

1. Line length
2. Braces
3. Indentation

- [x] `admin-ui-index` (0, 0, 3) #2424
- [x] `admin-ui` (501, 175, 425)
- [x] `adopter-statistics-impl` (0, 5) #2274
- [x] `animate-impl` (0, 0, 7) #2424
- [x] `annotation-impl` (41, 16, 7) #2701
- [x] `asset-manager-api` (46, 0, 0) #2419
- [x] `asset-manager-impl` (113, 16, 70) #2419
- [x] `asset-manager-storage-aws` (14, 8, 10) #2419
- [x] `asset-manager-storage-fs` (0, 3, 10) #2419
- [x] `asset-manager-workflowoperation` (0, 4, 0) #2419
- [x] `authorization-manager` (31, 10) #2270 
- [x] `authorization-xacml` (5, 2, 10) #2666
- [x] `caption-impl` (19, 34, 0)
- [x] `capture-admin-service-impl` (7, 23, 70)
- [x] `comments-workflowoperation` (11, 0, 0) #2424
- [x] `common-jpa-impl` (33, 16, 34) #2701
- [x] `common` (104, 497, 128)
- [x] `composer-ffmpeg` (279, 139, 50)
- [x] `composer-service-api` (15, 16, 0)
- [x] `composer-service-remote` (5, 4, 4)
- [x] `composer-workflowoperation` (55, 99, 44)
- [x] `conductor` (0, 5) #2274
- [x] `cover-image-impl` (11, 6) #2274
- [x] `cover-image-workflowoperation` (0, 21) #2274
- [x] `crop-api` (0, 2) #2274 
- [x] `crop-ffmpeg` (6, 0) #2274
- [x] `crop-workflowoperation` (2, 0) #2274
- [x] `db` (0, 9) #2273
- [x] `dictionary-hunspell` #2273
- [x] `dictionary-regexp` #2273
- [x] `distribution-service-api` (3, 0) #2340
- [x] `distribution-service-aws-s3-remote` #2273
- [x] `distribution-service-aws-s3` (38, 15) #2340
- [x] `distribution-service-download` (9, 15) #2340
- [x] `distribution-service-streaming-remote` #2273
- [x] `distribution-service-streaming-wowza` (22, 16) #2340
- [x] `distribution-workflowoperation` (35, 25) #2340
- [x] `dublincore` (42, 85, 26)
- [x] `email-template-service-impl` (4, 0, 0) #2424
- [x] `engage-theodul-core` (9, 0, 333) #2509
- [x] `engage-theodul-plugin-controls` (0, 0, 4) #2509
- [x] `engage-theodul-plugin-custom-matomo` (0, 0, 4) #2509
- [x] `engage-theodul-plugin-custom-mhConnection` (0, 0, 4) #2509
- [x] `engage-theodul-plugin-custom-notifications` (0, 0, 4) #2509
- [x] `engage-theodul-plugin-custom-usertracking` (0, 0, 4) #2509
- [x] `engage-theodul-plugin-description` (0, 0, 4) #2509
- [x] `engage-theodul-plugin-tab-description` (0, 0, 4) #2509
- [x] `engage-theodul-plugin-tab-shortcuts` (0, 0, 4) #2509
- [x] `engage-theodul-plugin-tab-slidetext` (0, 0, 4) #2509
- [x] `engage-theodul-plugin-timeline-statistics` (0, 0, 4) #2509
- [x] `engage-theodul-plugin-video-videojs` (0, 0, 4) #2509
- [x] `engage-ui` (0, 0, 7) #2424
- [x] `event-comment` (13, 29, 0) #2701
- [x] `execute-impl` (11, 19, 0)
- [x] `execute-remote` (5, 5, 0)
- [x] `execute-workflowoperation` (9, 18, 5)
- [x] `external-api` (314, 74, 64)
- [x] `fileupload` (21, 0, 43) #2701
- [x] `hello-world-impl` (0, 0, 8) #2424
- [x] `index-service` (73, 188, 23)
- [x] `ingest-download-service-impl` (6, 6, 0)
- [x] `ingest-download-service-workflowoperation` (2, 0, 0)
- [x] `ingest-service-impl` (167, 32, 82)
- [x] `inspection-service-ffmpeg` (16, 12, 15)
- [x] `inspection-service-remote` (0, 0, 4) #2424
- [x] `inspection-workflowoperation` (0, 3, 0) #2424
- [x] `kernel` (33, 53, 48)
- [x] `list-providers-service` (0, 13, 0) #2424
- [x] `live-schedule-impl` (22, 35, 0) #2666
- [x] `logging-workflowoperation` (0, 0, 4) #2424
- [x] `lti-service-impl` (25, 9, 0) #2420
- [x] `lti` (12, 0, 0) #2420
- [x] `message-broker-api` (3, 10, 0) #2701
- [x] `message-broker-impl` (0, 2, 22) #2701
- [x] `metadata-api` (0, 6, 0) #2424
- [x] `metadata` (0, 4, 4) #2424
- [x] `metrics-exporter` (0, 0, 4) #2424
- [x] `mpeg7` (33, 66, 0)
- [x] `notification-workflowoperation` (4, 2, 5) #2509
- [x] `oaipmh-persistence` (5, 17, 9)
- [x] `oaipmh` (19, 34, 2)
- [x] `presets` (4, 0, 0) #2424
- [x] `publication-service-api` (4, 0) #2338
- [x] `publication-service-configurable` #2338
- [x] `publication-service-oaipmh-remote` (4, 0) #2338
- [x] `publication-service-oaipmh` (40, 38) #2338
- [x] `publication-service-youtube-v3` (30, 4) #2338
- [x] `runtime-info` (18, 0, 4) #2666
- [x] `scheduler-api` (5, 0) #2273
- [x] `scheduler-impl` (213, 64, 29)
- [x] `scheduler-remote` (2, 10, 0)
- [x] `schema` (46, 53, 0)
- [x] `search-service-api` (2, 9, 0) #2506
- [x] `search-service-impl` (43, 190, 279) #2506
- [x] `search-service-remote` (2, 6, 0) #2506
- [x] `search` (0, 47, 0) #2506
- [x] `security-aai` (0, 8, 4) #2509
- [x] `security-shibboleth` (0, 2, 0) #2424
- [x] `series-service-api` (2, 0, 0) #2423
- [x] `series-service-impl` (65, 14, 17) #2423
- [x] `series-service-remote` (16, 19, 4) #2423
- [x] `serviceregistry` (133, 109, 27)
- [x] `shared-filesystem-utils` (2, 0, 0) #2424
- [x] `silencedetection-impl` (2, 2, 5) #2509
- [x] `smil-api` #2273
- [x] `smil-impl` (37, 0, 9) #2666
- [x] `smil-workflowoperation` (0, 1, 0) #2424
- [x] `sox-impl` (10, 21, 0) #2525
- [x] `sox-workflowoperation` (2, 9, 0)  #2525
- [x] `static-file-service-api` (15, 2, 0) #2525
- [x] `static-file-service-impl` (0, 3, 4) #2525
- [x] `static` (0, 3, 0) #2424
- [x] `statistics-export-service-impl` (21, 0, 4) #2666
- [x] `statistics-provider-influx` (5, 0, 0) #2666
- [x] `statistics-service-api` (3, 0, 20) #2666
- [x] `statistics-service-impl` (9, 0, 0) #2666
- [x] `statistics-service-remote` (4, 0, 0) #2666
- [x] `termination-state-aws` (20, 0, 0) #2666
- [x] `termination-state-impl` (5, 0, 0) #2666
- [x] `textanalyzer-impl` (4, 4) #2273
- [x] `textanalyzer-workflowoperation` (3, 12, 0) #2509
- [x] `textextractor-tesseract` (0, 3) #2273
- [x] `themes-workflowoperation` (3, 2, 0) #2424
- [x] `themes` (2, 7, 0) #2424
- [x] `timelinepreviews-api` (2, 0, 0) #2509
- [x] `timelinepreviews-ffmpeg` (2, 7, 11) #2509
- [x] `timelinepreviews-workflowoperation` (5, 0, 14) #2509
- [x] `transcription-service-amberscript` (4, 0, 20) #2700
- [x] `transcription-service-google-speech-impl` (27, 0, 7) #2700
- [x] `transcription-service-ibm-watson-impl` (24, 22, 0) #2700
- [x] `transcription-service-persistence` (12, 0, 7) #2700
- [x] `transcription-service-workflowoperation` (16, 14, 15) #2700
- [x] `urlsigning-common` (22, 0, 0) #2525
- [x] `urlsigning-service-api` (2, 0, 0) #2424
- [x] `urlsigning-service-impl` (48, 4, 2) #2525
- [x] `urlsigning-verifier-service-impl` (16, 0, 0) #2525
- [x] `user-interface-configuration` (3, 2, 0) #2509
- [x] `userdirectory-brightspace` (7, 0, 0) #2892
- [x] `userdirectory-canvas` (8, 0, 263) #2892
- [x] `userdirectory-ldap` (1, 31, 0) #2892
- [x] `userdirectory-moodle` (3, 30, 0) #2892
- [x] `userdirectory-sakai` (5, 6, 102) #2892
- [x] `userdirectory` (60, 74, 113) #2892
- [x] `usertracking-impl` (74, 28, 0)
- [x] `videoeditor-ffmpeg-impl` (5, 9, 11) #2525
- [x] `videoeditor-workflowoperation` (9, 7, 0) #2525
- [x] `videogrid-service-impl` (3, 3, 0) #2525
- [x] `videogrid-workflowoperation` (14, 16, 3) #2525
- [x] `videosegmenter-ffmpeg` (8, 5, 26) #2509
- [x] `waveform-ffmpeg` (5, 2, 11) #2509
- [x] `waveform-remote` (2, 0, 0) #2424
- [x] `waveform-workflowoperation` (10, 0, 9) #2509
- [x] `workflow-condition-parser` (5, 5, 0)
- [x] `workflow-service-api` (12, 82, 0)
- [x] `workflow-service-impl` (106, 49, 13)
- [x] `workflow-service-remote` (5, 25, 4)
- [x] `workflow-workflowoperation` (24, 18, 15)
- [x] `working-file-repository-service-impl` (55, 29, 8)
- [x] `working-file-repository-service-remote` (0, 4, 4)
- [x] `workspace-impl` (6, 9, 9) #2509

**Comment by gregorydlogan** [comment]
This appears to be done

**Comment by LukasKalbertodt** [comment]
Nope, it is unfortunately not done yet :/ 
[Checkstyle is still disabled for quite a number of modules](https://github.com/opencast/opencast/blob/019ab89f4ccdd4f755eb27dda9b5673c77c7b831/docs/checkstyle/checkstyle-suppressions.xml). I just didn't have time to work on this anymore.

**Comment by Arnei** [comment]
The list in the original post is now complete. There are still two more modules, `metadata` and `serviceregistry`, that are still suppressed and could be checkstyled (it's only indentation).
